version: '3.7'

services:
  redoc:
    image: redocly/redoc:v2.0.0-rc.41
    container_name: redoc
    environment:
      - SPEC_URL=https://petstore.swagger.io/v2/swagger.json
    ports:
      - 5555:80
    restart: unless-stopped
