-- Change session to Pluggable DataBase (PDB)
ALTER SESSION SET container = ORCLPDB1;

-- Create user
CREATE USER CS_DEV IDENTIFIED BY password1;
GRANT CONNECT, RESOURCE, DBA TO CS_DEV;
GRANT CREATE SESSION TO CS_DEV;
GRANT UNLIMITED TABLESPACE TO CS_DEV;
